// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkfYGGdR1XUQGUDq0DS5iTOR8Dz5KF5gI',
    appId: '1:942050053807:web:d5c9ae698c186683b20e5a',
    messagingSenderId: '942050053807',
    projectId: 'smart-home-334c9',
    authDomain: 'smart-home-334c9.firebaseapp.com',
    storageBucket: 'smart-home-334c9.appspot.com',
    measurementId: 'G-K0HK8RSSLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQtEh6nVUIMap0m7hIjE-mPjzCs9CwKf4',
    appId: '1:942050053807:android:c3d601b4cb1438b2b20e5a',
    messagingSenderId: '942050053807',
    projectId: 'smart-home-334c9',
    storageBucket: 'smart-home-334c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2aTrVbRozY-AEtTSehMNyVQMV1yBui68',
    appId: '1:942050053807:ios:bfeb93485e0e272ab20e5a',
    messagingSenderId: '942050053807',
    projectId: 'smart-home-334c9',
    storageBucket: 'smart-home-334c9.appspot.com',
    iosBundleId: 'com.example.smartHomeEnergyMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2aTrVbRozY-AEtTSehMNyVQMV1yBui68',
    appId: '1:942050053807:ios:bfeb93485e0e272ab20e5a',
    messagingSenderId: '942050053807',
    projectId: 'smart-home-334c9',
    storageBucket: 'smart-home-334c9.appspot.com',
    iosBundleId: 'com.example.smartHomeEnergyMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkfYGGdR1XUQGUDq0DS5iTOR8Dz5KF5gI',
    appId: '1:942050053807:web:f38e68cec64e8719b20e5a',
    messagingSenderId: '942050053807',
    projectId: 'smart-home-334c9',
    authDomain: 'smart-home-334c9.firebaseapp.com',
    storageBucket: 'smart-home-334c9.appspot.com',
    measurementId: 'G-8Q8CFQ3H38',
  );
}
